[package]
name = "topos"
version = "0.1"
lean_version = "leanprover-community/lean:3.6.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d909a61200168cdcf6f6d22813ae1989a112eb8e"}
